const lessonTitle = "雨树";

const lessonData = [
    // ===== 第1段 =====
    ["在", "zài", "Among", "Di"],
    ["众多", "zhòng duō", "many", "banyak"],
    ["的", "de", "", ""],
    ["树木", "shù mù", "trees", "pokok"],
    ["中", "zhōng", "among", "antara"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["最", "zuì", "most", "paling"],
    ["喜爱", "xǐ ài", "love", "suka"],
    ["雨树", "yǔ shù", "Rain Tree", "Pokok Hujan"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["它", "tā", "it", "ia"],
    ["最能", "zuì néng", "best can", "paling boleh"],
    ["表现", "biǎo xiàn", "express", "menunjukkan"],
    ["南洋", "nán yáng", "Nanyang", "Nanyang"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "manusia"],
    ["与", "yǔ", "and", "dan"],
    ["万物", "wàn wù", "all things", "segala benda"],
    ["的", "de", "", ""],
    ["生态", "shēng tài", "ecology", "ekologi"],
    ["与", "yǔ", "and", "dan"],
    ["文化", "wén huà", "culture", "budaya"],
    ["。", "", "", ""],
    ["到", "dào", "To", "Ke"],
    ["欧洲", "ōu zhōu", "Europe", "Eropah"],
    ["旅行", "lǚ xíng", "travel", "melancong"],
    ["，", "", "", ""],
    ["古老", "gǔ lǎo", "ancient", "tua"],
    ["的", "de", "", ""],
    ["教堂", "jiào táng", "church", "gereja"],
    ["是", "shì", "is", "ialah"],
    ["必要", "bì yào", "necessary", "perlu"],
    ["参观的", "cān guān de", "to visit", "dilawati"],
    ["，", "", "", ""],
    ["它是", "tā shì", "it is", "ia adalah"],
    ["欧洲人", "ōu zhōu rén", "Europeans", "orang Eropah"],
    ["历史文化", "lì shǐ wén huà", "history and culture", "sejarah dan budaya"],
    ["的", "de", "", ""],
    ["象征", "xiàng zhēng", "symbol", "lambang"],
    ["。", "", "", ""],
    ["雨树", "yǔ shù", "Rain Tree", "Pokok Hujan"],
    ["在我看来", "zài wǒ kàn lái", "in my view", "pada pandangan saya"],
    ["，", "", "", ""],
    ["就是", "jiù shì", "is", "ialah"],
    ["热带雨林", "rè dài yǔ lín", "tropical rainforest", "hutan hujan tropika"],
    ["的", "de", "", ""],
    ["古老教堂", "gǔ lǎo jiào táng", "ancient church", "gereja tua"],
    ["，", "", "", ""],
    ["在", "zài", "on", "pada"],
    ["每一棵树上", "měi yī kē shù shàng", "every tree", "setiap pokok"],
    ["，", "", "", ""],
    ["您可以", "nín kě yǐ", "you can", "awak boleh"],
    ["找到", "zhǎo dào", "find", "menemui"],
    ["热带人", "rè dài rén", "tropical people", "orang tropika"],
    ["的", "de", "", ""],
    ["信仰", "xìn yǎng", "beliefs", "kepercayaan"],
    ["、", "", "", ""],
    ["生活习惯", "shēng huó xí guàn", "living habits", "cara hidup"],
    ["，", "", "", ""],
    ["甚至", "shèn zhì", "even", "malahan"],
    ["神话", "shén huà", "myths", "mitos"],
    ["与", "yǔ", "and", "dan"],
    ["梦想", "mèng xiǎng", "dreams", "impian"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["我", "wǒ", "I", "saya"],
    ["每次", "měi cì", "every time", "setiap kali"],
    ["到", "dào", "to", "ke"],
    ["机场", "jī chǎng", "airport", "lapangan terbang"],
    ["迎接", "yíng jiē", "receive", "menyambut"],
    ["初次", "chū cì", "first time", "kali pertama"],
    ["来访的", "lái fǎng de", "visiting", "datang melawat"],
    ["朋友", "péng yǒu", "friends", "kawan"],
    ["，", "", "", ""],
    ["通向", "tōng xiàng", "leading to", "menuju ke"],
    ["市区", "shì qū", "city", "bandar"],
    ["的", "de", "", ""],
    ["大道上", "dà dào shàng", "main road", "jalan besar"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["一定", "yí dìng", "surely", "pasti"],
    ["介绍", "jiè shào", "introduce", "memperkenalkan"],
    ["矗立", "chù lì", "standing tall", "berdiri tegak"],
    ["两旁", "liǎng páng", "on both sides", "di kedua-dua sisi"],
    ["的", "de", "", ""],
    ["雨树", "yǔ shù", "Rain Trees", "Pokok Hujan"],
    ["。", "", "", ""],
    ["每一棵树的", "měi yī kē shù de", "Every tree's", "Setiap pokok punya"],
    ["叶冠", "yè guān", "leaf canopy", "kanopi daun"],
    ["，", "", "", ""],
    ["向", "xiàng", "towards", "ke"],
    ["四方八面", "sì fāng bā miàn", "all directions", "pelbagai arah"],
    ["伸展", "shēn zhǎn", "spread", "merebak"],
    ["，", "", "", ""],
    ["茂密的", "mào mì de", "dense", "tebal"],
    ["叶", "yè", "leaves", "daun"],
    ["形成", "xíng chéng", "forming", "membentuk"],
    ["一把", "yī bǎ", "a", "sebuah"],
    ["巨大", "jù dà", "huge", "besar"],
    ["的", "de", "", ""],
    ["绿色雨伞", "lǜ sè yǔ sǎn", "green umbrella", "payung hijau"],
    ["，", "", "", ""],
    ["酷阳高照时", "kù yáng gāo zhào shí", "when the sun blazes", "ketika matahari terik"],
    ["，", "", "", ""],
    ["投下", "tóu xià", "cast", "memberi"],
    ["一大片", "yī dà piàn", "a large area of", "sebidang luas"],
    ["阴凉", "yīn liáng", "shady and cool", "teduh dan sejuk"],
    ["的", "de", "", ""],
    ["树影", "shù yǐng", "shade", "bayang-bayang"],
    ["，", "", "", ""],
    ["下一阵", "xià yī zhèn", "when there is", "apabila berlaku"],
    ["难以预测", "nán yǐ yù cè", "unpredictable", "sukar diramal"],
    ["的", "de", "", ""],
    ["过云雨", "guò yún yǔ", "passing shower", "hujan panas"],
    ["时", "shí", "when", "ketika"],
    ["，", "", "", ""],
    ["树下", "shù xià", "under the tree", "bawah pokok"],
    ["往往", "wǎng wǎng", "often", "sering"],
    ["可以", "kě yǐ", "can", "boleh"],
    ["当作", "dàng zuò", "as", "sebagai"],
    ["躲避雨水的", "duǒ bì yǔ shuǐ de", "shelter from rain", "tempat berteduh"],
    ["篷盖", "péng gài", "shelter", "timbunan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["每一棵树", "měi yī kē shù", "Every tree", "Setiap pokok"],
    ["对", "duì", "to", "bagi"],
    ["原始土著", "yuán shǐ tǔ zhù", "primitive natives", "orang asli"],
    ["和", "hé", "and", "dan"],
    ["早期的", "zǎo qī de", "early", "awal"],
    ["华族移民", "huá zú yí mín", "Chinese immigrants", "pendatang Cina"],
    ["来说", "lái shuō", "for", "bagi"],
    ["，", "", "", ""],
    ["就是", "jiù shì", "is", "ialah"],
    ["一座", "yī zuò", "a", "sebuah"],
    ["报时", "bào shí", "time-telling", "memberitahu masa"],
    ["的", "de", "", ""],
    ["大钟楼", "dà zhōng lóu", "clock tower", "menara jam"],
    ["。", "", "", ""],
    ["下午", "xià wǔ", "In the afternoon", "Pada waktu petang"],
    ["当", "dāng", "when", "apabila"],
    ["雨树", "yǔ shù", "rain tree", "pokok hujan"],
    ["对称的", "duì chèn de", "symmetrical", "simetri"],
    ["叶子", "yè zi", "leaves", "daun"],
    ["合闭起来", "hé bì qǐ lái", "close", "tertutup"],
    ["，", "", "", ""],
    ["如", "rú", "like", "seperti"],
    ["人们祈祷时", "rén men qí dǎo shí", "when people pray", "ketika orang berdoa"],
    ["合着的手掌", "hé zhe de shǒu zhǎng", "folded palms", "tapak tangan yang berlipat"],
    ["，", "", "", ""],
    ["这时", "zhè shí", "this time", "pada masa ini"],
    ["是", "shì", "is", "ialah"],
    ["五点的时刻", "wǔ diǎn de shí kè", "five o'clock", "pukul lima"],
    ["，", "", "", ""],
    ["因此", "yīn cǐ", "therefore", "maka"],
    ["这种树", "zhè zhǒng shù", "this tree", "pokok ini"],
    ["的", "de", "", ""],
    ["俗名", "sú míng", "common name", "nama biasa"],
    ["叫", "jiào", "is called", "dipanggil"],
    ["Pukul Lima", "pukul lima", "Pukul Lima", "Pukul Lima"],
    ["（", "", "", ""],
    ["马来语", "mǎ lái yǔ", "Malay", "Bahasa Melayu"],
    ["）", "", "", ""],
    ["，", "", "", ""],
    ["意思是", "yì si shì", "meaning", "bermakna"],
    ["“", "", "", ""],
    ["五点钟", "wǔ diǎn zhōng", "five o'clock", "pukul lima"],
    ["”", "", "", ""],
    ["。", "", "", ""],
    ["每天清晨", "měi tiān qīng chén", "Every morning", "Setiap pagi"],
    ["大约", "dà yuē", "about", "kira-kira"],
    ["五点钟", "wǔ diǎn zhōng", "five o'clock", "pukul lima"],
    ["，", "", "", ""],
    ["它的叶子", "tā de yè zi", "its leaves", "daunnya"],
    ["就", "jiù", "then", "lalu"],
    ["打开", "dǎ kāi", "open", "terbuka"],
    ["，", "", "", ""],
    ["所以", "suǒ yǐ", "so", "maka"],
    ["树叶", "shù yè", "leaves", "daun"],
    ["一闭一开", "yī bì yī kāi", "open and close", "tertutup dan terbuka"],
    ["，", "", "", ""],
    ["给人", "gěi rén", "give people", "memberi orang"],
    ["报告了", "bào gào le", "tell", "memberitahu"],
    ["时间", "shí jiān", "time", "masa"],
    ["。", "", "", ""],
    ["而这时间", "ér zhè shí jiān", "and this time", "dan masa ini"],
    ["正是", "zhèng shì", "is exactly", "itulah"],
    ["热带人", "rè dài rén", "tropical people", "orang tropika"],
    ["日出而作", "rì chū ér zuò", "start work at sunrise", "bekerja ketika matahari terbit"],
    ["，", "", "", ""],
    ["日落而息", "rì luò ér xī", "rest at sunset", "berehat ketika matahari terbenam"],
    ["的时候", "de shí hou", "time", "masa"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["巨大的", "jù dà de", "Huge", "Besar"],
    ["雨树", "yǔ shù", "Rain Tree", "Pokok Hujan"],
    ["，", "", "", ""],
    ["原来", "yuán lái", "originally", "rupanya"],
    ["是", "shì", "is", "ialah"],
    ["由", "yóu", "from", "daripada"],
    ["含羞草", "hán xiū cǎo", "mimosa plant", "pokok malu"],
    ["的", "de", "", ""],
    ["突变", "tū biàn", "mutation", "mutasi"],
    ["而成", "ér chéng", "evolved", "berevolusi"],
    ["，", "", "", ""],
    ["因此", "yīn cǐ", "therefore", "maka"],
    ["叶子的", "yè zi de", "the leaves", "daun punya"],
    ["感受", "gǎn shòu", "sensitivity", "sensitiviti"],
    ["与", "yǔ", "with", "dengan"],
    ["含羞草", "hán xiū cǎo", "mimosa", "pokok malu"],
    ["一样", "yī yàng", "same", "sama"],
    ["细微", "xì wēi", "subtle", "halus"],
    ["和", "hé", "and", "dan"],
    ["敏感", "mǐn gǎn", "sensitive", "sensitif"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["羽状对生", "yǔ zhuàng duì shēng", "pinnate and opposite", "berbentuk bulu dan bertentangan"],
    ["的", "de", "", ""],
    ["小叶子", "xiǎo yè zi", "small leaves", "daun kecil"],
    ["，", "", "", ""],
    ["因", "yīn", "due to", "kerana"],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["的", "de", "", ""],
    ["强弱", "qiáng ruò", "strength", "kekuatan"],
    ["而", "ér", "to", "untuk"],
    ["有所反应", "yǒu suǒ fǎn yìng", "respond", "memberi reaksi"],
    ["。", "", "", ""],
    ["太阳", "tài yáng", "Sun", "Matahari"],
    ["光亮时", "guāng liàng shí", "when bright", "apabila terang"],
    ["，", "", "", ""],
    ["叶子", "yè zi", "leaves", "daun"],
    ["水平地", "shuǐ píng de", "horizontally", "secara mendatar"],
    ["张开", "zhāng kāi", "spread open", "terbuka"],
    ["；", "", "", ""],
    ["当天阴下雨", "dāng tiān yīn xià yǔ", "when cloudy or raining", "apabila mendung atau hujan"],
    ["或", "huò", "or", "atau"],
    ["黄昏时分", "huáng hūn shí fēn", "at dusk", "pada waktu senja"],
    ["，", "", "", ""],
    ["对称的", "duì chèn de", "symmetrical", "simetri"],
    ["叶子", "yè zi", "leaves", "daun"],
    ["便", "biàn", "then", "lalu"],
    ["合起来", "hé qǐ lái", "close up", "tertutup"],
    ["。", "", "", ""],
    ["由于", "yóu yú", "Because", "Kerana"],
    ["下雨", "xià yǔ", "rain", "hujan"],
    ["和", "hé", "and", "dan"],
    ["夜晚", "yè wǎn", "night", "malam"],
    ["紧闭着", "jǐn bì zhe", "tightly closed", "tertutup rapat"],
    ["的", "de", "", ""],
    ["叶子", "yè zi", "leaves", "daun"],
    ["藏着", "cáng zhe", "contain", "menyimpan"],
    ["雨露", "yǔ lù", "rain and dew", "air hujan dan embun"],
    ["，", "", "", ""],
    ["白天", "bái tiān", "daytime", "pada siang hari"],
    ["叶子张开", "yè zi zhāng kāi", "leaves open", "daun terbuka"],
    ["，", "", "", ""],
    ["便有雨", "biàn yǒu yǔ", "there will be rain", "akan ada hujan"],
    ["落下", "luò xià", "fall", "jatuh"],
    ["，", "", "", ""],
    ["雨树", "yǔ shù", "Rain Tree", "Pokok Hujan"],
    ["这名称", "zhè míng chēng", "this name", "nama ini"],
    ["便", "biàn", "then", "maka"],
    ["由此而来", "yóu cǐ ér lái", "comes from this", "berasal daripada ini"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["南洋居民", "nán yáng jū mín", "Nanyang residents", "Penduduk Nanyang"],
    ["与", "yǔ", "and", "dan"],
    ["雨树的", "yǔ shù de", "Rain Tree's", "Pokok Hujan punya"],
    ["年龄", "nián líng", "age", "usia"],
    ["最难", "zuì nán", "most difficult", "paling sukar"],
    ["隐藏", "yǐn cáng", "to hide", "menyembunyikan"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["年龄一大", "nián líng yī dà", "once old", "apabila usia tua"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu"],
    ["得了", "dé le", "get", "mendapat"],
    ["风湿病", "fēng shī bìng", "rheumatism", "sakit sendi"],
    ["。", "", "", ""],
    ["二三十年老的", "èr sān shí nián lǎo de", "twenty or thirty years old", "berusia dua tiga puluh tahun"],
    ["，", "", "", ""],
    ["都会", "dōu huì", "will", "akan"],
    ["因潮湿", "yīn cháo shī", "due to dampness", "kerana lembap"],
    ["寄生着", "jì shēng zhe", "host", "menumpang"],
    ["各种各类", "gè zhǒng gè lèi", "various kinds of", "pelbagai jenis"],
    ["羊齿植物", "yáng chǐ zhí wù", "ferns", "paku-pakis"],
    ["、", "", "", ""],
    ["胡姬花草", "hú jī huā cǎo", "orchids", "bunga orkid"],
    ["，", "", "", ""],
    ["其中", "qí zhōng", "among them", "antaranya"],
    ["以", "yǐ", "with", "dengan"],
    ["看起来", "kàn qǐ lái", "looks like", "kelihatan seperti"],
    ["像羚羊", "xiàng líng yáng", "like an antelope", "seperti kijang"],
    ["的", "de", "", ""],
    ["凤尾草", "fèng wěi cǎo", "fern", "paku ekor merak"],
    ["最吸引人", "zuì xī yǐn rén", "most attractive", "paling menarik"],
    ["。", "", "", ""],
    ["这种迹象", "zhè zhǒng jì xiàng", "This sign", "Tanda ini"],
    ["跟", "gēn", "with", "dengan"],
    ["叶子", "yè zi", "leaves", "daun"],
    ["的一开一闭", "de yī kāi yī bì", "opening and closing", "terbuka dan tertutup"],
    ["有关系", "yǒu guān xì", "is related", "berkaitan"],
    ["，", "", "", ""],
    ["每天", "měi tiān", "every day", "setiap hari"],
    ["从", "cóng", "from", "dari"],
    ["叶子张开时", "yè zi zhāng kāi shí", "when leaves open", "apabila daun terbuka"],
    ["滴在", "dī zài", "drip on", "menitik di"],
    ["树干上的", "shù gàn shàng de", "the trunk", "batang pokok"],
    ["雨露", "yǔ lù", "rain and dew", "air hujan dan embun"],
    ["，", "", "", ""],
    ["造成", "zào chéng", "causing", "menyebabkan"],
    ["树干", "shù gàn", "trunk", "batang pokok"],
    ["高度的", "gāo dù de", "high", "yang tinggi"],
    ["潮湿", "cháo shī", "dampness", "kelembapan"],
    ["。", "", "", ""],
    ["二三十年老的", "èr sān shí nián lǎo de", "Twenty or thirty years old", "Berusia dua tiga puluh tahun"],
    ["雨树上", "yǔ shù shàng", "rain tree", "pokok hujan"],
    ["寄生植物", "jì shēng zhí wù", "host plants", "tumbuhan tumpang"],
    ["种类之多", "zhǒng lèi zhī duō", "so many kinds", "begitu banyak jenis"],
    ["，", "", "", ""],
    ["简直", "jiǎn zhí", "simply", "sungguh"],
    ["就是", "jiù shì", "is", "ialah"],
    ["一个", "yī gè", "an", "sebuah"],
    ["空中植物园", "kōng zhōng zhí wù yuán", "aerial botanical garden", "taman botani udara"],
    ["，", "", "", ""],
    ["美丽极了", "měi lì jí le", "very beautiful", "sangat cantik"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["普遍的", "pǔ biàn de", "Common", "Biasa"],
    ["草木", "cǎo mù", "plants", "tumbuhan"],
    ["，", "", "", ""],
    ["都以花", "dōu yǐ huā", "all use flowers", "semua menggunakan bunga"],
    ["向人炫耀", "xiàng rén xuàn yào", "show off to people", "menunjuk kepada orang"],
    ["，", "", "", ""],
    ["雨树", "yǔ shù", "Rain Tree", "Pokok Hujan"],
    ["却不然", "què bù rán", "but not", "sebaliknya"],
    ["，", "", "", ""],
    ["它红白相间", "tā hóng bái xiāng jiàn", "its red and white", "merah dan putih berselang-seli"],
    ["扇形的花", "shàn xíng de huā", "fan-shaped flowers", "bunga berbentuk kipas"],
    ["，", "", "", ""],
    ["都开在", "dōu kāi zài", "all bloom on", "semua mekar di"],
    ["向上伸展的", "xiàng shàng shēn zhǎn de", "upward-stretching", "yang menjulang ke atas"],
    ["枝头上", "zhī tóu shàng", "branches", "dahan"],
    ["，", "", "", ""],
    ["它的花", "tā de huā", "its flowers", "bunganya"],
    ["只开给", "zhǐ kāi gěi", "only bloom for", "hanya mekar untuk"],
    ["小鸟", "xiǎo niǎo", "birds", "burung"],
    ["和", "hé", "and", "dan"],
    ["云朵看", "yún duǒ kàn", "clouds to see", "awan melihat"],
    ["！", "", "", ""],
    ["怪不得", "guài bu de", "no wonder", "tidak hairanlah"],
    ["雨树上的", "yǔ shù shàng de", "on the rain tree", "di atas pokok hujan"],
    ["鸟声", "niǎo shēng", "bird song", "bunyi burung"],
    ["特别", "tè bié", "especially", "terutamanya"],
    ["嘹亮", "liáo liàng", "loud and clear", "nyaring"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["在", "zài", "In", "Di"],
    ["旷野里", "kuàng yě lǐ", "the wilderness", "padang terbuka"],
    ["自由生长的", "zì yóu shēng zhǎng de", "freely growing", "tumbuh secara bebas"],
    ["雨树", "yǔ shù", "Rain Tree", "Pokok Hujan"],
    ["，", "", "", ""],
    ["其", "qí", "its", "ia punya"],
    ["树冠之大", "shù guàn zhī dà", "canopy size", "saiz kanopi"],
    ["可", "kě", "can", "boleh"],
    ["占满", "zhàn mǎn", "occupy", "memenuhi"],
    ["一个", "yī gè", "a", "sebuah"],
    ["足球场", "zú qiú chǎng", "football field", "padang bola sepak"],
    ["，", "", "", ""],
    ["而且", "ér qiě", "and", "dan"],
    ["枝丫低垂", "zhī yā dī chuí", "branches hanging low", "dahan-dahan melabuh rendah"],
    ["，", "", "", ""],
    ["在", "zài", "in", "di"],
    ["马来西亚", "mǎ lái xī yà", "Malaysia", "Malaysia"],
    ["的", "de", "", ""],
    ["乡间公路旁", "xiāng jiān gōng lù páng", "countryside roadsides", "tepi jalan di luar bandar"],
    ["的", "de", "", ""],
    ["雨树", "yǔ shù", "Rain Trees", "Pokok Hujan"],
    ["，", "", "", ""],
    ["有时", "yǒu shí", "sometimes", "kadang-kadang"],
    ["形成", "xíng chéng", "form", "membentuk"],
    ["绿色的隧道", "lǜ sè de suì dào", "green tunnel", "terowong hijau"],
    ["，", "", "", ""],
    ["可惜", "kě xī", "unfortunately", "sayang"],
    ["这种", "zhè zhǒng", "this kind of", "jenis ini"],
    ["霸气的雨树", "bà qì de yǔ shù", "majestic rain tree", "pokok hujan yang gagah"],
    ["逐渐地", "zhú jiàn de", "gradually", "beransur-ansur"],
    ["消失了", "xiāo shī le", "disappeared", "hilang"],
    ["。", "", "", ""],
    ["为了", "wèi le", "In order to", "Untuk"],
    ["适合", "shì hé", "suit", "menyesuaikan"],
    ["有限的", "yǒu xiàn de", "limited", "terhad"],
    ["空间", "kōng jiān", "space", "ruang"],
    ["和", "hé", "and", "dan"],
    ["土地", "tǔ dì", "land", "tanah"],
    ["，", "", "", ""],
    ["为了方便", "wèi le fāng biàn", "for the convenience of", "untuk memudahkan"],
    ["高大的", "gāo dà de", "tall", "besar"],
    ["重型车辆", "zhòng xíng chē liàng", "heavy vehicles", "kenderaan berat"],
    ["之行驶", "zhī xíng shǐ", "to travel", "untuk bergerak"],
    ["，", "", "", ""],
    ["雨树的", "yǔ shù de", "rain tree's", "pokok hujan punya"],
    ["枝干", "zhī gàn", "branches", "dahan"],
    ["经常", "jīng cháng", "often", "sering"],
    ["遭受", "zāo shòu", "suffer", "mengalami"],
    ["修剪的噩运", "xiū jiǎn de è yùn", "pruning misfortune", "nasib buruk dipotong"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["只能", "zhǐ néng", "can only", "hanya boleh"],
    ["向高空", "xiàng gāo kōng", "towards the sky", "ke udara tinggi"],
    ["发展", "fā zhǎn", "develop", "berkembang"],
    ["，", "", "", ""],
    ["不能", "bù néng", "cannot", "tidak boleh"],
    ["接近", "jiē jìn", "approach", "mendekati"],
    ["土地", "tǔ dì", "the ground", "tanah"],
    ["。", "", "", ""],
    ["雨树生态", "yǔ shù shēng tài", "Rain tree ecology", "Ekologi pokok hujan"],
    ["之改变", "zhī gǎi biàn", "change", "perubahan"],
    ["，", "", "", ""],
    ["与我们", "yǔ wǒ men", "with us", "dengan kita"],
    ["这些", "zhè xiē", "these", "ini"],
    ["生长在", "shēng zhǎng zài", "growing in", "tumbuh di"],
    ["热带上", "rè dài shàng", "the tropics", "kawasan tropika"],
    ["热情奔放", "rè qíng bēn fàng", "passionate", "bersemangat"],
    ["的", "de", "", ""],
    ["人的生态", "rén de shēng tài", "people's ecology", "ekologi manusia"],
    ["是一样的", "shì yī yàng de", "is the same", "adalah sama"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["王润华", "wáng rùn huá", "Wang Runhua", "Wang Runhua"],
    ["《", "", "", ""],
    ["雨树", "yǔ shù", "Rain Tree", "Pokok Hujan"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
